### ISSUE TITLE
Schema typos

### ISSUE THREAD

**Issue by duncan-grant** [manitou-mail/manitou-mail-mdx#1]
I've found a couple of typos in Schema.pm master branch (1.5.0):
@@ 286
-"mailing_definition"=> <<'EOT'
+"mailing_definition" => <<'EOT'
@@ 356
-CREATE TABLE tags_archive_counters (
+CREATE TABLE tags_archive_counters_queue (

Also, I think some of the version numbers need updating.

Interesting project!

**Comment by manitou-mail** [comment]
Thanks for the report!
Fixed by commit 6509144
